name: Merge Staging to Production

on:
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
          # We need the token to push changes back
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git user
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Switch to production branch
        run: git checkout production

      - name: Pull latest production changes
        run: git pull origin production

      - name: Merge staging into production
        run: |
          # Attempt the merge
          git merge --no-ff staging -m "Merge staging into production via GitHub Action ${GITHUB_RUN_ID}"

      - name: Push changes to production
        run: git push origin production 