name: Slack Channel Sync

on:
  schedule:
    # Run at midnight Pacific time (UTC-7/8)
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.15.4
          run_install: false # Wait for node setup before running install

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Sync configured channels
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          DB_URL: ${{ secrets.DB_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "Running sync for all configured channels"
          # Add more channels as needed
          pnpm sync:slack introductions
          pnpm sync:slack general
