name: Test Slack Notify

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: failing step
        run: exit 1
  notify-slack-on-failure:
    name: Notify Slack on Failure
    runs-on: ubuntu-latest
    if: ${{ always() && (needs.sync.result == 'failure' || needs.sync.result == 'timed_out') }}
    needs:
      - sync
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_USERNAME: Fabric
          MSG_MINIMAL: actions url
          SLACK_TITLE: Nightly Sync Failed
          SLACK_MESSAGE: Check GH Action logs via link above for more detail
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_COLOR: failure
          SLACK_FOOTER: ""
